version: "3.9"

name: One Piece Chat

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./apps/api/.env
    depends_on:
      - redis
      - mongo

volumes:
  mongo-data:
